# Remember!
# Rules must be individualized
# and don't forget to control OUTPUT ;)
# localhost 23.09.2023
---

- name: Configuration iptables for web
  hosts: virtualbox
  become: yes
  gather_facts: false
  tasks:
    
    - name: Allow lo int *INPUT*
      ansible.builtin.iptables:
        chain: INPUT
        action: insert
        in_interface: lo
        jump: "ACCEPT"

    - name: Allow est/rel *INPUT*
      ansible.builtin.iptables:
        chain: INPUT
        action: append
        ctstate: ["ESTABLISHED,RELATED"]
        jump: "ACCEPT"

    - name: Allow ssh *INPUT*
      ansible.builtin.iptables:
        chain: INPUT
        action: append
        protocol: tcp
        destination_port: 22
        jump: "ACCEPT"

    - name: Allow HTTP and HTTPS *INPUT*
      ansible.builtin.iptables:
        chain: INPUT
        action: append
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
        jump: ACCEPT

    - name: Drop policy *INPUT*
      ansible.builtin.iptables:
        action: append
        chain: INPUT 
        policy: "DROP" 

    - name: Drop policy *INPUT*
      ansible.builtin.iptables:
        action: append
        chain: FORWARD 
        policy: "DROP"
